online-mode=false
server-port=0
enable-query=false
enable-rcon=false
enable-status=false
level-name=qualification-world
gamemode=survival
difficulty=peaceful
spawn-protection=0
view-distance=2
simulation-distance=2
sync-chunk-writes=true
max-players=1
motd=MaddPrestige disposable qualification
