package net.maddkraft.maddprestige.core.admin.ui;

public enum GuiActionKind {
    VIEW_PROGRESS,
    SIMULATE_RANK_UP,
    SIMULATE_PRESTIGE,
    PREPARE_RANK_UP,
    PREPARE_PRESTIGE,
    CONFIRM_PRESTIGE,
    BACK_PLAYER,
    CLOSE_PLAYER,
    VIEW_DOCTOR,
    VIEW_CONFIGURATION,
    EDIT_CONFIGURATION,
    ADD_CONFIGURATION_VALUE,
    REMOVE_CONFIGURATION_VALUE,
    ADD_CONFIGURATION_OBJECT,
    EDIT_CONFIGURATION_OBJECT,
    REMOVE_CONFIGURATION_OBJECT,
    ADD_STAGE,
    PREVIEW_CONFIGURATION,
    PREPARE_CONFIGURATION_ACKNOWLEDGEMENT,
    CONFIRM_CONFIGURATION_ACKNOWLEDGEMENT,
    APPLY_CONFIGURATION,
    ROLLBACK_CONFIGURATION,
    SELECT_STAGE_REMAP,
    REMOVE_STAGE_REMAP,
    DELETE_STAGE
}
