package net.maddkraft.maddprestige.core.authorization;

import java.util.Locale;

/** Stable machine-readable identity for a public RankUp or Prestige authorization rejection. */
public enum AuthorizationBlockerKind {
    NO_ACTIVE_STAGE_SNAPSHOT,
    NO_ACTIVE_PRESTIGE_CONFIGURATION,
    STALE_PROVIDER_BINDING,
    PLAYER_STAGE_STATE_LOAD_FAILED,
    PLAYER_STAGE_STATE_MISSING,
    PLAYER_PRESTIGE_STATE_UNAVAILABLE,
    STAGE_LADDER_INACTIVE,
    PRESTIGE_DISABLED,
    CURRENT_STAGE_UNKNOWN,
    CURRENT_STAGE_DISABLED,
    NO_LEGAL_NEXT_STAGE,
    ILLEGAL_OR_STALE_TARGET,
    TARGET_STAGE_UNKNOWN_OR_DISABLED,
    PRESTIGE_STAGE_INELIGIBLE,
    PRESTIGE_MAXIMUM_REACHED,
    PRESTIGE_COUNTER_OVERFLOW,
    STAGE_REVISION_OVERFLOW,
    PRESTIGE_REVISION_OVERFLOW,
    PRESTIGE_COOLDOWN_ACTIVE,
    UNKNOWN_CONFIGURED_COST,
    UNKNOWN_CONFIGURED_REWARD,
    UNKNOWN_REQUIREMENT_TREE,
    TRUSTED_CONTEXT_LOAD_FAILED,
    TRUSTED_CONTEXT_MISMATCH,
    REQUIRED_PROVIDER_UNAVAILABLE,
    REQUIREMENT_UNSATISFIED,
    REQUIREMENT_PROVENANCE_MISSING,
    REQUIREMENT_PLAYER_MISMATCH,
    REQUIREMENT_REVISION_MISMATCH,
    REQUIREMENT_PROVIDER_GENERATION_MISMATCH,
    REQUIREMENT_TREE_MISMATCH,
    COST_PROVIDER_CONTRACT_MISSING,
    COST_DEFINITION_INVALID,
    COST_PROVIDER_VALIDATION_FAILED,
    COST_PREFLIGHT_BLOCKED,
    COST_PLAN_INTEGRITY_VIOLATION,
    COST_PREFLIGHT_FAILED,
    REWARD_PROVIDER_CONTRACT_MISSING,
    REWARD_DEFINITION_INVALID,
    REWARD_PROVIDER_VALIDATION_FAILED,
    REWARD_PREFLIGHT_BLOCKED,
    REWARD_PLAN_INTEGRITY_VIOLATION,
    REWARD_PREFLIGHT_FAILED,
    RANK_PROJECTION_BINDING_INCOMPLETE,
    RANK_PROJECTION_CONTRACT_MISSING,
    RANK_PROJECTION_INVALID,
    PRESTIGE_RANK_PROJECTION_UNAVAILABLE,
    BOUNDARY_PROVIDER_UNAVAILABLE,
    BOUNDARY_READ_FAILED,
    BOUNDARY_SAMPLE_UNAVAILABLE,
    UNKNOWN;

    public String catalogIdentity() {
        return name().toLowerCase(Locale.ROOT);
    }
}
